import Head from 'next/head'
import Image from 'next/image'
import Layout from '../components/layout'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Personal Website</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="titlecard">
        <h1 className="title">Hi I'm Luke</h1>
      </div>
      <div>
        
      </div>

    
    </div>
  )
}
